'use strict';
// Testi del wizard di configurazione, inglese (predefinito) e italiano.
// Le istruzioni sui menu del controller seguono la guida TP-Link "How to Create Site in Omada
// Controller via Open API" (Settings > Platform Integration > Open API > Add New App).

const WIZARD = {
  en: {
    app: 'Guest portal setup',
    passo: (n, t) => `Step ${n} of ${t}`,
    indietro: 'Back', continua: 'Continue', segretoSalvato: 'Leave empty to keep the saved value.',
    sessione: 'The setup session expired: enter the setup code again.',
    origine: 'The request came from another page: reload this page and try again.',
    accesso: {
      titolo: 'Enter the setup code',
      testo: 'To make sure only you can configure the portal, the container printed a one-time setup code in its log.',
      istruzioni: ['Run <code>docker logs &lt;container&gt;</code> (with Docker Compose: <code>docker compose logs</code>).', 'Copy the code from the line “Setup code”.'],
      campo: 'Setup code', bottone: 'Start setup',
      errato: 'Wrong code.', bloccato: 'Too many wrong attempts: wait 10 minutes and try again.',
    },
    controller: {
      titolo: 'Omada controller',
      testo: 'The address of the Omada controller that manages the guest Wi-Fi access points, as you open it in the browser.',
      campo: 'Controller address',
      aiuto: 'For example https://192.168.0.10:8043 for a software controller, or https://192.168.0.2 for an OC200/OC300. A self-signed certificate is fine.',
      vuoto: 'Enter the controller address.',
      irraggiungibile: d => `The container can’t reach the controller at this address (${d}). Check the address and that the container can reach that network.`,
      nonOmada: d => `This address answers (${d}), but it isn’t an Omada controller.`,
      trovato: v => `Omada controller ${v} found.`,
    },
    openapi: {
      titolo: 'Open API application',
      testo: 'The portal reads device details and creates its operator through the controller’s Open API. Create an application for it:',
      istruzioni: [
        'In the controller switch to the <b>Global</b> view and open <b>Settings › Platform Integration › Open API</b>.',
        'Click <b>Add New App</b>. Give it a name (for example “Guest portal”), choose mode <b>Client</b>, role <b>Administrator</b>, and in <b>Site Privileges</b> the site with the guest Wi-Fi.',
        'Save, click the eye icon next to the new app and copy the <b>Client ID</b> and the <b>Client Secret</b>.',
      ],
      nota: 'With the Administrator role the wizard can create the hotspot operator for you. With a Viewer role, create the operator yourself (Hotspot › Operators) and choose “existing operator” later.',
      id: 'Client ID', segreto: 'Client Secret', vuoto: 'Enter both Client ID and Client Secret.',
      credenziali: d => `The controller refused these credentials (${d}). Check that the app uses Client mode and that ID and Secret are copied in full.`,
      nessunSito: 'The credentials work, but the app can’t see any site: give it the guest Wi-Fi site in Site Privileges.',
    },
    sito: { titolo: 'Site', testo: 'Choose the site that broadcasts the guest Wi-Fi.', scegli: 'Choose a site.' },
    ssid: {
      titolo: 'Guest network',
      testo: 'Choose the guest SSID. The portal only accepts guests coming from this network.',
      ospitiSi: 'Guest Network on', ospitiNo: 'Guest Network off', aperta: 'open', protetta: 'password',
      avviso: 'Guest Network is off on this SSID: guests would not be isolated from each other and could reach your LAN. Turn it on in the SSID settings before going live.',
      nessuno: 'There is no SSID on this site yet: create the guest SSID in the controller, then reload this page.',
      scegli: 'Choose an SSID.',
    },
    operatore: {
      titolo: 'Hotspot operator',
      testo: 'The portal approves guests with a hotspot operator account of the controller.',
      crea: 'Create one for me', creaDesc: 'An operator named “guest-portal” with a long random password, for this site only.',
      esistente: 'Use an existing operator', esistenteDesc: 'One you created in Hotspot › Operators.',
      nome: 'Operator name', password: 'Password', vuoto: 'Enter name and password of the operator.',
      creazione: d => `The controller didn’t create the operator (${d}). If the Open API app has the Viewer role, create the operator in Hotspot › Operators and choose “existing operator”.`,
      login: d => `Login with this operator failed (${d}).`,
      fatto: n => `Operator “${n}” ready.`,
    },
    telegram: {
      titolo: 'Telegram bot',
      testo: 'Requests arrive on Telegram with buttons to approve or reject them. Use a bot dedicated to this portal: if another program reads the same bot (Home Assistant, n8n…), the buttons stop working.',
      istruzioni: [
        'In Telegram open <b>@BotFather</b> and send <code>/newbot</code>.',
        'Choose a display name, then a username ending in “bot”.',
        'BotFather answers with a token like <code>123456789:AA…</code>: paste it here.',
      ],
      campo: 'Bot token', formatoToken: 'This doesn’t look like a bot token (numbers, a colon, then letters and digits).',
      telegram: d => `Telegram doesn’t accept this token (${d}).`,
      telegramIrraggiungibile: d => `The container can’t reach Telegram (${d}).`,
      pronto: u => `Bot @${u} is ready.`,
      webhook: d => `This bot already sends its messages to another program through a webhook (${d}), so the portal’s buttons would not work. Create a bot dedicated to the portal.`,
    },
    chat: {
      titolo: 'Where requests arrive',
      testo: u => `Tell @${u} where to write:`,
      istruzioni: u => [
        `<b>Private chat</b>: open <b>@${u}</b> in Telegram and press <b>Start</b>.`,
        `<b>Group</b>: add <b>@${u}</b> to the group as an administrator, then write a message in the group, or in the topic you want to use.`,
        'Then press <b>Find chats</b>.',
      ],
      cerca: 'Find chats',
      nessuna: 'No messages yet. Write to the bot as described above, then press “Find chats” again.',
      conflitto: d => `Another program is reading this bot right now (${d}). Stop it, or use a different bot.`,
      privata: n => `Private chat with ${n}`, gruppo: t => `Group “${t}”`, topic: (n, t) => `Topic “${n || '?'}” in “${t}”`,
      daChi: n => `written by ${n}`,
      manuale: 'Enter the IDs yourself', chatId: 'Chat ID', threadId: 'Topic ID (optional)',
      admin: 'Owner’s user ID', adminAiuto: 'The owner can press the buttons from anywhere. It is taken from who wrote the message.',
      lingua: 'Language of the messages', scegli: 'Choose a chat, or enter its ID.',
      invia: 'Send a test message and continue',
      prova: s => `✅ <b>${s}</b> · guest Wi-Fi access requests will arrive here.`,
      errInvio: d => `Telegram didn’t deliver the test message (${d}).`,
    },
    regole: {
      titolo: 'Rules',
      durate: 'Access durations (hours)', durateAiuto: 'Offered as buttons, separated by commas, for example 4,24.',
      attesa: 'A request with no answer expires after (minutes)',
      pausa: 'After a rejection the same device waits (minutes)',
      max: 'Maximum requests waiting at the same time',
      numeri: 'Use whole numbers greater than zero.',
    },
    riepilogo: {
      titolo: 'Review and save',
      voci: { OMADA_URL: 'Controller', OMADA_SITE_ID: 'Site', SSID: 'Guest SSID', HOTSPOT_USER: 'Hotspot operator', BOT: 'Telegram bot', TG_CHAT: 'Chat', TG_THREAD: 'Topic', TG_LANG: 'Message language', DURATE: 'Durations (hours)' },
      ambiente: k => `These values come from environment variables, which override the saved file: ${k}.`,
      daFare: 'Still to do in the controller',
      passi: (h, s) => [
        `<b>Portal</b> (Authentication › Portal): add a portal with authentication type <b>External Portal Server</b>, address <code>${h.host}</code> and port <code>${h.porta}</code>, on SSID <b>${s}</b>.`,
        `<b>Access rule</b> (ACL, EAP ACL): allow TCP from SSID <b>${s}</b> to <code>${h.host}:${h.porta}</code> and to the controller’s portal ports (8088 and 8843 by default). Without it Guest Network blocks the portal itself.`,
      ],
      ospitiNo: s => `<b>Guest Network</b>: turn it on for SSID <b>${s}</b>, so guests are isolated and kept off your LAN.`,
      salva: 'Save and start the portal',
    },
    fatto: {
      titolo: 'Saved',
      testo: 'The configuration is saved and the portal is running: guests can now ask for access. You can close this page.',
      ancora: 'To change the configuration later, create the file <code>/data/setup</code> in the container and restart it: <code>docker exec &lt;container&gt; touch /data/setup</code>, then <code>docker restart &lt;container&gt;</code>.',
    },
  },
  it: {
    app: 'Configurazione del portale',
    passo: (n, t) => `Passo ${n} di ${t}`,
    indietro: 'Indietro', continua: 'Continua', segretoSalvato: 'Lascia vuoto per tenere il valore salvato.',
    sessione: 'La sessione di configurazione è scaduta: inserisci di nuovo il codice.',
    origine: 'La richiesta arriva da un’altra pagina: ricarica questa pagina e riprova.',
    accesso: {
      titolo: 'Inserisci il codice di configurazione',
      testo: 'Perché solo tu possa configurare il portale, il container ha scritto nel suo log un codice da usare una volta sola.',
      istruzioni: ['Esegui <code>docker logs &lt;container&gt;</code> (con Docker Compose: <code>docker compose logs</code>).', 'Copia il codice dalla riga “Setup code”.'],
      campo: 'Codice di configurazione', bottone: 'Inizia',
      errato: 'Codice sbagliato.', bloccato: 'Troppi tentativi sbagliati: aspetta 10 minuti e riprova.',
    },
    controller: {
      titolo: 'Controller Omada',
      testo: 'L’indirizzo del controller Omada che gestisce gli access point della Wi-Fi ospiti, come lo apri nel browser.',
      campo: 'Indirizzo del controller',
      aiuto: 'Per esempio https://192.168.0.10:8043 per un software controller, oppure https://192.168.0.2 per un OC200/OC300. Il certificato autofirmato va bene.',
      vuoto: 'Inserisci l’indirizzo del controller.',
      irraggiungibile: d => `Il container non raggiunge il controller a questo indirizzo (${d}). Controlla l’indirizzo e che il container veda quella rete.`,
      nonOmada: d => `Questo indirizzo risponde (${d}), ma non è un controller Omada.`,
      trovato: v => `Trovato il controller Omada ${v}.`,
    },
    openapi: {
      titolo: 'Applicazione Open API',
      testo: 'Il portale legge i dati dei dispositivi e crea il suo operatore tramite l’Open API del controller. Crea un’applicazione apposta:',
      istruzioni: [
        'Nel controller passa alla vista <b>Global</b> e apri <b>Settings › Platform Integration › Open API</b>.',
        'Premi <b>Add New App</b>. Dai un nome (per esempio “Portale ospiti”), scegli la modalità <b>Client</b>, il ruolo <b>Administrator</b> e in <b>Site Privileges</b> il sito con la Wi-Fi ospiti.',
        'Salva, premi l’icona dell’occhio accanto alla nuova app e copia <b>Client ID</b> e <b>Client Secret</b>.',
      ],
      nota: 'Con il ruolo Administrator il wizard può creare per te l’operatore hotspot. Con il ruolo Viewer crea tu l’operatore (Hotspot › Operators) e più avanti scegli “operatore esistente”.',
      id: 'Client ID', segreto: 'Client Secret', vuoto: 'Inserisci sia Client ID sia Client Secret.',
      credenziali: d => `Il controller rifiuta queste credenziali (${d}). Controlla che l’app sia in modalità Client e che ID e Secret siano copiati per intero.`,
      nessunSito: 'Le credenziali funzionano ma l’app non vede nessun sito: assegnale il sito della Wi-Fi ospiti in Site Privileges.',
    },
    sito: { titolo: 'Sito', testo: 'Scegli il sito che trasmette la Wi-Fi ospiti.', scegli: 'Scegli un sito.' },
    ssid: {
      titolo: 'Rete ospiti',
      testo: 'Scegli l’SSID per gli ospiti. Il portale accetta solo ospiti che arrivano da questa rete.',
      ospitiSi: 'Guest Network attivo', ospitiNo: 'Guest Network spento', aperta: 'aperta', protetta: 'con password',
      avviso: 'Su questo SSID Guest Network è spento: gli ospiti non sarebbero isolati tra loro e potrebbero raggiungere la tua rete. Attivalo nelle impostazioni dell’SSID prima di aprire la rete.',
      nessuno: 'In questo sito non c’è ancora nessun SSID: crea l’SSID ospiti nel controller, poi ricarica questa pagina.',
      scegli: 'Scegli un SSID.',
    },
    operatore: {
      titolo: 'Operatore hotspot',
      testo: 'Il portale approva gli ospiti con un account operatore hotspot del controller.',
      crea: 'Crealo tu', creaDesc: 'Un operatore “guest-portal” con una password lunga e casuale, solo per questo sito.',
      esistente: 'Usa un operatore esistente', esistenteDesc: 'Uno creato da te in Hotspot › Operators.',
      nome: 'Nome dell’operatore', password: 'Password', vuoto: 'Inserisci nome e password dell’operatore.',
      creazione: d => `Il controller non ha creato l’operatore (${d}). Se l’app Open API ha il ruolo Viewer, crea l’operatore in Hotspot › Operators e scegli “operatore esistente”.`,
      login: d => `L’accesso con questo operatore non riesce (${d}).`,
      fatto: n => `Operatore “${n}” pronto.`,
    },
    telegram: {
      titolo: 'Bot Telegram',
      testo: 'Le richieste arrivano su Telegram con i bottoni per approvarle o rifiutarle. Usa un bot dedicato a questo portale: se un altro programma legge lo stesso bot (Home Assistant, n8n…), i bottoni smettono di funzionare.',
      istruzioni: [
        'In Telegram apri <b>@BotFather</b> e manda <code>/newbot</code>.',
        'Scegli un nome visualizzato, poi uno username che finisce con “bot”.',
        'BotFather risponde con un token come <code>123456789:AA…</code>: incollalo qui.',
      ],
      campo: 'Token del bot', formatoToken: 'Non sembra il token di un bot (numeri, due punti, poi lettere e cifre).',
      telegram: d => `Telegram non accetta questo token (${d}).`,
      telegramIrraggiungibile: d => `Il container non raggiunge Telegram (${d}).`,
      pronto: u => `Il bot @${u} è pronto.`,
      webhook: d => `Questo bot manda già i suoi messaggi a un altro programma tramite webhook (${d}), quindi i bottoni del portale non funzionerebbero. Crea un bot dedicato al portale.`,
    },
    chat: {
      titolo: 'Dove arrivano le richieste',
      testo: u => `Indica a @${u} dove scrivere:`,
      istruzioni: u => [
        `<b>Chat privata</b>: apri <b>@${u}</b> in Telegram e premi <b>Avvia</b>.`,
        `<b>Gruppo</b>: aggiungi <b>@${u}</b> al gruppo come amministratore, poi scrivi un messaggio nel gruppo, o nel topic che vuoi usare.`,
        'Poi premi <b>Cerca le chat</b>.',
      ],
      cerca: 'Cerca le chat',
      nessuna: 'Ancora nessun messaggio. Scrivi al bot come descritto sopra, poi premi di nuovo “Cerca le chat”.',
      conflitto: d => `In questo momento un altro programma sta leggendo questo bot (${d}). Fermalo, oppure usa un altro bot.`,
      privata: n => `Chat privata con ${n}`, gruppo: t => `Gruppo “${t}”`, topic: (n, t) => `Topic “${n || '?'}” in “${t}”`,
      daChi: n => `scritto da ${n}`,
      manuale: 'Inserisci tu gli ID', chatId: 'ID della chat', threadId: 'ID del topic (facoltativo)',
      admin: 'ID utente del proprietario', adminAiuto: 'Il proprietario può premere i bottoni da qualsiasi chat. Si ricava da chi ha scritto il messaggio.',
      lingua: 'Lingua dei messaggi', scegli: 'Scegli una chat, oppure inserisci il suo ID.',
      invia: 'Manda un messaggio di prova e continua',
      prova: s => `✅ <b>${s}</b> · le richieste di accesso alla Wi-Fi ospiti arriveranno qui.`,
      errInvio: d => `Telegram non ha consegnato il messaggio di prova (${d}).`,
    },
    regole: {
      titolo: 'Regole',
      durate: 'Durate dell’accesso (ore)', durateAiuto: 'Diventano i bottoni, separate da virgole, per esempio 4,24.',
      attesa: 'Una richiesta senza risposta scade dopo (minuti)',
      pausa: 'Dopo un rifiuto lo stesso dispositivo aspetta (minuti)',
      max: 'Richieste in attesa al massimo nello stesso momento',
      numeri: 'Usa numeri interi maggiori di zero.',
    },
    riepilogo: {
      titolo: 'Controlla e salva',
      voci: { OMADA_URL: 'Controller', OMADA_SITE_ID: 'Sito', SSID: 'SSID ospiti', HOTSPOT_USER: 'Operatore hotspot', BOT: 'Bot Telegram', TG_CHAT: 'Chat', TG_THREAD: 'Topic', TG_LANG: 'Lingua dei messaggi', DURATE: 'Durate (ore)' },
      ambiente: k => `Questi valori arrivano da variabili d’ambiente, che hanno la precedenza sul file salvato: ${k}.`,
      daFare: 'Ancora da fare nel controller',
      passi: (h, s) => [
        `<b>Portale</b> (Authentication › Portal): aggiungi un portale con autenticazione <b>External Portal Server</b>, indirizzo <code>${h.host}</code> e porta <code>${h.porta}</code>, sull’SSID <b>${s}</b>.`,
        `<b>Regola di accesso</b> (ACL, EAP ACL): permetti il TCP dall’SSID <b>${s}</b> verso <code>${h.host}:${h.porta}</code> e verso le porte del portale del controller (8088 e 8843 di serie). Senza, Guest Network blocca anche il portale.`,
      ],
      ospitiNo: s => `<b>Guest Network</b>: attivalo sull’SSID <b>${s}</b>, così gli ospiti restano isolati e fuori dalla tua rete.`,
      salva: 'Salva e avvia il portale',
    },
    fatto: {
      titolo: 'Salvato',
      testo: 'La configurazione è salvata e il portale è attivo: gli ospiti possono già chiedere l’accesso. Puoi chiudere questa pagina.',
      ancora: 'Per cambiare la configurazione più avanti, crea il file <code>/data/setup</code> nel container e riavvialo: <code>docker exec &lt;container&gt; touch /data/setup</code>, poi <code>docker restart &lt;container&gt;</code>.',
    },
  },
};

module.exports = { WIZARD };
